### ISSUE TITLE
关于微信小程序登录态验证流程使用场景

### ISSUE THREAD

**Issue by TechZi** [cantoo/learning#1]
请教 “[微信小程序登录态验证流程](https://github.com/cantoo/learning/blob/master/wxapp/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%99%BB%E5%BD%95%E6%80%81%E9%AA%8C%E8%AF%81%E6%B5%81%E7%A8%8B.md)” 这个流程是用在什么场景下的？能否举几个例子？

**Comment by cantoo** [comment]
文章写于小程序刚推出, 随后微信官方推出了推荐的登录验证流程
https://mp.weixin.qq.com/debug/wxadoc/dev/api/api-login.html#wxchecksessionobject
