### ISSUE TITLE
关于openid的表述，你的表述好像不对吧？

### ISSUE THREAD

**Issue by baizhiqiang** [cantoo/learning#2]
个人感觉你关于openID的表述是有问题的，openid不应该发送的小程序端的，小程序和服务端的authorization好像应该只用token吧。

**Comment by cantoo** [comment]
文章写于小程序刚推出, 随后微信官方推出了推荐的登录验证流程
https://mp.weixin.qq.com/debug/wxadoc/dev/api/api-login.html#wxchecksessionobject
